<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $countries = Country::pluck('id', 'iso_code');

        $suppliers = [
            [
                'name' => 'Shenzhen Electronics Co., Ltd.',
                'country_id' => $countries['CN'] ?? 1,
                'contact_email' => 'procurement@sz-electronics.cn',
                'category' => 'Electronics',
                'reliability_score' => 88,
                'on_time_delivery_pct' => 96.5,
                'quality_rating' => 92,
                'lead_time_days' => 21,
                'certification' => 'ISO 9001, ISO 14001',
            ],
            [
                'name' => 'Mumbai Textile Exports',
                'country_id' => $countries['IN'] ?? 2,
                'contact_email' => 'info@mumbai-textile.in',
                'category' => 'Textile',
                'reliability_score' => 75,
                'on_time_delivery_pct' => 88.0,
                'quality_rating' => 80,
                'lead_time_days' => 35,
                'certification' => 'ISO 9001',
            ],
            [
                'name' => 'Jakarta Logistics Supply',
                'country_id' => $countries['ID'] ?? 3,
                'contact_email' => 'supply@jaklog.co.id',
                'category' => 'Logistics',
                'reliability_score' => 82,
                'on_time_delivery_pct' => 92.0,
                'quality_rating' => 85,
                'lead_time_days' => 14,
                'certification' => null,
            ],
            [
                'name' => 'Bangkok Automotive Parts',
                'country_id' => $countries['TH'] ?? 4,
                'contact_email' => 'parts@bkk-auto.th',
                'category' => 'Automotive',
                'reliability_score' => 90,
                'on_time_delivery_pct' => 98.5,
                'quality_rating' => 95,
                'lead_time_days' => 10,
                'certification' => 'ISO 9001, ISO 14001, IATF 16949',
            ],
            [
                'name' => 'Ho Chi Minh Garment Factory',
                'country_id' => $countries['VN'] ?? 5,
                'contact_email' => 'sales@hcm-garment.vn',
                'category' => 'Textile',
                'reliability_score' => 70,
                'on_time_delivery_pct' => 85.0,
                'quality_rating' => 78,
                'lead_time_days' => 45,
                'certification' => null,
            ],
            [
                'name' => 'Singapore Precision Engineering',
                'country_id' => $countries['SG'] ?? 6,
                'contact_email' => 'eng@sg-precision.sg',
                'category' => 'Electronics',
                'reliability_score' => 95,
                'on_time_delivery_pct' => 99.0,
                'quality_rating' => 98,
                'lead_time_days' => 7,
                'certification' => 'ISO 9001, ISO 13485, AS9100D',
            ],
            [
                'name' => 'Kuala Lumpur Palm Oil Supply',
                'country_id' => $countries['MY'] ?? 7,
                'contact_email' => 'trade@kl-palmoil.my',
                'category' => 'Commodities',
                'reliability_score' => 78,
                'on_time_delivery_pct' => 90.0,
                'quality_rating' => 82,
                'lead_time_days' => 20,
                'certification' => 'ISO 9001, RSPO',
            ],
            [
                'name' => 'Tokyo Advanced Materials',
                'country_id' => $countries['JP'] ?? 8,
                'contact_email' => 'materials@tokyo-adv.jp',
                'category' => 'Chemicals',
                'reliability_score' => 93,
                'on_time_delivery_pct' => 98.0,
                'quality_rating' => 96,
                'lead_time_days' => 12,
                'certification' => 'ISO 9001, ISO 14001, ISO 45001',
            ],
            [
                'name' => 'Seoul Semiconductor Corp.',
                'country_id' => $countries['KR'] ?? 53,
                'contact_email' => 'sales@seoul-semi.kr',
                'category' => 'Electronics',
                'reliability_score' => 91,
                'on_time_delivery_pct' => 97.0,
                'quality_rating' => 94,
                'lead_time_days' => 14,
                'certification' => 'ISO 9001, ISO 14001',
            ],
            [
                'name' => 'Taipei Component Manufacturing',
                'country_id' => $countries['TW'] ?? 57,
                'contact_email' => 'info@taipei-component.tw',
                'category' => 'Electronics',
                'reliability_score' => 87,
                'on_time_delivery_pct' => 95.5,
                'quality_rating' => 90,
                'lead_time_days' => 18,
                'certification' => 'ISO 9001',
            ],
            [
                'name' => 'Los Angeles Logistics Hub',
                'country_id' => $countries['US'] ?? 63,
                'contact_email' => 'ops@la-logistics.us',
                'category' => 'Logistics',
                'reliability_score' => 85,
                'on_time_delivery_pct' => 93.0,
                'quality_rating' => 88,
                'lead_time_days' => 5,
                'certification' => 'ISO 9001, C-TPAT',
            ],
            [
                'name' => 'Hamburg Marine Engineering',
                'country_id' => $countries['DE'] ?? 21,
                'contact_email' => 'eng@hamburg-marine.de',
                'category' => 'Industrial',
                'reliability_score' => 94,
                'on_time_delivery_pct' => 98.5,
                'quality_rating' => 97,
                'lead_time_days' => 21,
                'certification' => 'ISO 9001, ISO 14001, ISO 45001, TÜV',
            ],
            [
                'name' => 'London Commodity Trading',
                'country_id' => $countries['GB'] ?? 62,
                'contact_email' => 'trade@london-commodity.co.uk',
                'category' => 'Commodities',
                'reliability_score' => 80,
                'on_time_delivery_pct' => 91.0,
                'quality_rating' => 84,
                'lead_time_days' => 10,
                'certification' => 'ISO 9001',
            ],
            [
                'name' => 'Rotterdam Chemical Supply',
                'country_id' => $countries['NL'] ?? 38,
                'contact_email' => 'supply@rotterdam-chemical.nl',
                'category' => 'Chemicals',
                'reliability_score' => 89,
                'on_time_delivery_pct' => 96.0,
                'quality_rating' => 92,
                'lead_time_days' => 15,
                'certification' => 'ISO 9001, ISO 14001, REACH',
            ],
            [
                'name' => 'Dubai Logistics & Trading',
                'country_id' => $countries['AE'] ?? 61,
                'contact_email' => 'info@dubai-logistics.ae',
                'category' => 'Logistics',
                'reliability_score' => 83,
                'on_time_delivery_pct' => 92.0,
                'quality_rating' => 86,
                'lead_time_days' => 8,
                'certification' => 'ISO 9001',
            ],
            [
                'name' => 'São Paulo Auto Components',
                'country_id' => $countries['BR'] ?? 13,
                'contact_email' => 'vendas@sp-autoparts.br',
                'category' => 'Automotive',
                'reliability_score' => 72,
                'on_time_delivery_pct' => 86.0,
                'quality_rating' => 79,
                'lead_time_days' => 30,
                'certification' => 'ISO 9001',
            ],
            [
                'name' => 'Mexico City Electronics Assembly',
                'country_id' => $countries['MX'] ?? 36,
                'contact_email' => 'ventas@mx-electronics.mx',
                'category' => 'Electronics',
                'reliability_score' => 76,
                'on_time_delivery_pct' => 89.0,
                'quality_rating' => 82,
                'lead_time_days' => 25,
                'certification' => null,
            ],
            [
                'name' => 'Cape Town Mining Supplies',
                'country_id' => $countries['ZA'] ?? 52,
                'contact_email' => 'supply@ct-mining.za',
                'category' => 'Industrial',
                'reliability_score' => 74,
                'on_time_delivery_pct' => 87.0,
                'quality_rating' => 80,
                'lead_time_days' => 28,
                'certification' => 'ISO 9001',
            ],
            [
                'name' => 'Lagos Petroleum Logistics',
                'country_id' => $countries['NG'] ?? 40,
                'contact_email' => 'ops@lagos-petro.ng',
                'category' => 'Energy',
                'reliability_score' => 65,
                'on_time_delivery_pct' => 80.0,
                'quality_rating' => 72,
                'lead_time_days' => 40,
                'certification' => null,
            ],
            [
                'name' => 'Manila Garment Exports',
                'country_id' => $countries['PH'] ?? 44,
                'contact_email' => 'exports@manila-garment.ph',
                'category' => 'Textile',
                'reliability_score' => 71,
                'on_time_delivery_pct' => 85.0,
                'quality_rating' => 77,
                'lead_time_days' => 35,
                'certification' => null,
            ],
            [
                'name' => 'Istanbul Automotive Supply',
                'country_id' => $countries['TR'] ?? 59,
                'contact_email' => 'info@istanbul-auto.tr',
                'category' => 'Automotive',
                'reliability_score' => 79,
                'on_time_delivery_pct' => 90.0,
                'quality_rating' => 83,
                'lead_time_days' => 22,
                'certification' => 'ISO 9001, ISO 14001',
            ],
            [
                'name' => 'Warsaw Industrial Parts',
                'country_id' => $countries['PL'] ?? 45,
                'contact_email' => 'sales@warsaw-industrial.pl',
                'category' => 'Industrial',
                'reliability_score' => 84,
                'on_time_delivery_pct' => 93.0,
                'quality_rating' => 87,
                'lead_time_days' => 16,
                'certification' => 'ISO 9001',
            ],
            [
                'name' => 'Karachi Textile Mills',
                'country_id' => $countries['PK'] ?? 42,
                'contact_email' => 'info@karachi-textile.pk',
                'category' => 'Textile',
                'reliability_score' => 68,
                'on_time_delivery_pct' => 82.0,
                'quality_rating' => 75,
                'lead_time_days' => 42,
                'certification' => null,
            ],
            [
                'name' => 'Dhaka Ready Garments',
                'country_id' => $countries['BD'] ?? 9,
                'contact_email' => 'orders@dhaka-garments.bd',
                'category' => 'Textile',
                'reliability_score' => 67,
                'on_time_delivery_pct' => 81.0,
                'quality_rating' => 74,
                'lead_time_days' => 50,
                'certification' => 'ISO 9001, WRAP',
            ],
            [
                'name' => 'Alexandria Chemicals & Fertilizers',
                'country_id' => $countries['EG'] ?? 18,
                'contact_email' => 'sales@alex-chemicals.eg',
                'category' => 'Chemicals',
                'reliability_score' => 73,
                'on_time_delivery_pct' => 86.0,
                'quality_rating' => 78,
                'lead_time_days' => 30,
                'certification' => 'ISO 9001',
            ],
            [
                'name' => 'Nairobi Coffee & Commodities',
                'country_id' => $countries['KE'] ?? 33,
                'contact_email' => 'trade@nairobi-commodities.ke',
                'category' => 'Commodities',
                'reliability_score' => 69,
                'on_time_delivery_pct' => 83.0,
                'quality_rating' => 76,
                'lead_time_days' => 25,
                'certification' => null,
            ],
            [
                'name' => 'Milan Fashion Textiles',
                'country_id' => $countries['IT'] ?? 30,
                'contact_email' => 'export@milan-fashion.it',
                'category' => 'Textile',
                'reliability_score' => 86,
                'on_time_delivery_pct' => 94.0,
                'quality_rating' => 91,
                'lead_time_days' => 14,
                'certification' => 'ISO 9001, OEKO-TEX',
            ],
            [
                'name' => 'Lyon Chemical Products',
                'country_id' => $countries['FR'] ?? 20,
                'contact_email' => 'supply@lyon-chemicals.fr',
                'category' => 'Chemicals',
                'reliability_score' => 88,
                'on_time_delivery_pct' => 95.0,
                'quality_rating' => 90,
                'lead_time_days' => 12,
                'certification' => 'ISO 9001, ISO 14001, REACH',
            ],
            [
                'name' => 'Barcelona Food & Beverage Supply',
                'country_id' => $countries['ES'] ?? 54,
                'contact_email' => 'info@barcelona-food.es',
                'category' => 'Commodities',
                'reliability_score' => 81,
                'on_time_delivery_pct' => 91.5,
                'quality_rating' => 85,
                'lead_time_days' => 10,
                'certification' => 'ISO 9001, FSSC 22000',
            ],
            [
                'name' => 'Sydney Mining Equipment',
                'country_id' => $countries['AU'] ?? 6,
                'contact_email' => 'sales@sydney-mining.au',
                'category' => 'Industrial',
                'reliability_score' => 90,
                'on_time_delivery_pct' => 96.0,
                'quality_rating' => 93,
                'lead_time_days' => 20,
                'certification' => 'ISO 9001, AS/NZS 4801',
            ],
            [
                'name' => 'Guangzhou Consumer Electronics',
                'country_id' => $countries['CN'] ?? 1,
                'contact_email' => 'sales@gz-electronics.cn',
                'category' => 'Electronics',
                'reliability_score' => 84,
                'on_time_delivery_pct' => 93.5,
                'quality_rating' => 87,
                'lead_time_days' => 18,
                'certification' => 'ISO 9001, CCC',
            ],
            [
                'name' => 'Chennai Automotive Castings',
                'country_id' => $countries['IN'] ?? 24,
                'contact_email' => 'castings@chennai-auto.in',
                'category' => 'Automotive',
                'reliability_score' => 77,
                'on_time_delivery_pct' => 88.5,
                'quality_rating' => 81,
                'lead_time_days' => 28,
                'certification' => 'ISO 9001, IATF 16949',
            ],
            [
                'name' => 'Pusan Maritime Logistics',
                'country_id' => $countries['KR'] ?? 53,
                'contact_email' => 'ops@pusan-logistics.kr',
                'category' => 'Logistics',
                'reliability_score' => 92,
                'on_time_delivery_pct' => 97.5,
                'quality_rating' => 95,
                'lead_time_days' => 6,
                'certification' => 'ISO 9001, ISO 14001',
            ],
            [
                'name' => 'Amsterdam Food Processing',
                'country_id' => $countries['NL'] ?? 38,
                'contact_email' => 'info@amsterdam-food.nl',
                'category' => 'Commodities',
                'reliability_score' => 87,
                'on_time_delivery_pct' => 94.5,
                'quality_rating' => 90,
                'lead_time_days' => 8,
                'certification' => 'ISO 9001, FSSC 22000, Organic',
            ],
        ];

        foreach ($suppliers as $data) {
            Supplier::create($data);
        }
    }
}
